name:                ContratosFinancieros
version:             0.1.0.0
github:              "Bussita/EDSL-contratos-financieros-en-Haskell"
license:             MIT
author:              "Santiago Bussanich"
maintainer:          "santiagobussanich321@gmail.com"
copyright:           "2026 Santiago Bussanich"

extra-source-files:
- README.md

description:         Financial Contracts EDSL in Haskell

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.14
- containers >= 0.6
- time >= 1.9
- text >= 1.2
- mtl
- transformers
- haskeline
- exceptions
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - AST
    - Parser
    - PrettyPrinter
    - Evaluator
    - Monads
    - Types
    - Exportar
    - ExportarAST

executables:
  financial-contracts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ContratosFinancieros
    - mtl
    - haskeline
    - exceptions

